# Generated by Django 3.2.13 on 2022-06-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumni_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('pic', models.CharField(max_length=500)),
                ('id_pic', models.CharField(max_length=500)),
                ('reg_date', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('dob', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=500)),
                ('pin', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='alumni_ideas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alumni_user_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('pic', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=30)),
                ('tm', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='alumni_job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('job_title', models.CharField(max_length=100)),
                ('org_name', models.CharField(max_length=100)),
                ('org_addr', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='batch_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
                ('yr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='batch_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
                ('yr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='college_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=500)),
                ('pin', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='event_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=30)),
                ('tm', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='event_pics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('pic', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='job_vaccancy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1500)),
                ('desc', models.CharField(max_length=1500)),
                ('pic', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=30)),
                ('tm', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='noticeboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('pic', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=30)),
                ('tm', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('pic', models.CharField(max_length=500)),
                ('id_pic', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=25)),
                ('reg_date', models.CharField(max_length=25)),
                ('course', models.CharField(max_length=25)),
                ('dob', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=500)),
                ('pin', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='student_posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('pic', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=30)),
                ('tm', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id1', models.IntegerField()),
                ('user_id2', models.IntegerField()),
                ('msg', models.CharField(max_length=1500)),
                ('dt', models.CharField(max_length=30)),
                ('tm', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('addr', models.CharField(max_length=500)),
                ('pin', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=25)),
                ('u_type', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
