# Generated by Django 3.2.13 on 2022-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_login_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_details',
        ),
        migrations.DeleteModel(
            name='student_posts',
        ),
        migrations.DeleteModel(
            name='user_chat',
        ),
        migrations.AddField(
            model_name='college_details',
            name='url',
            field=models.CharField(default='12', max_length=100),
            preserve_default=False,
        ),
    ]
