# Generated by Django 3.2.13 on 2022-06-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_college_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_details',
            name='pic_path',
            field=models.CharField(default=1, max_length=130),
            preserve_default=False,
        ),
    ]
