# Generated by Django 3.2.13 on 2022-06-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_event_details_pic_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='batch_details',
        ),
    ]
