# Generated by Django 3.2.13 on 2022-06-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_batch_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni_details',
            name='batch',
        ),
    ]
