# Generated by Django 3.2.13 on 2022-06-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_alumni_details_batch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alumni_ideas',
        ),
        migrations.DeleteModel(
            name='batch_master',
        ),
        migrations.DeleteModel(
            name='job_vaccancy',
        ),
        migrations.DeleteModel(
            name='noticeboard',
        ),
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
