# Generated by Django 3.2.13 on 2022-07-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_branch_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni_details',
            name='branch_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
