# Generated by Django 3.2.13 on 2022-07-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alumni_details_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni_details',
            name='pass_year',
            field=models.CharField(default=2021, max_length=25),
            preserve_default=False,
        ),
    ]
