# Generated by Django 3.2.13 on 2022-07-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alumni_details_pass_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumni_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('alumni_id', models.IntegerField()),
                ('pic_path', models.CharField(max_length=100)),
                ('descr', models.CharField(max_length=200)),
            ],
        ),
    ]
